workflows:
  build:
    name: "Build App"
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "main"
          include: true
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build Android APK
        script: |
          flutter build apk
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - johesteb@gmail.com
        notify:
          success: true
          failure: false
